### PR TITLE
feat: Integrate env to improve AWS IMDS interaction

### PR DESCRIPTION
**Pull request by mageshwaran-lifebit**
JIRA: https://lifebit.atlassian.net/browse/LP-6169

### CODE REVIEW

**Review by tiagofilipe12 — COMMENTED** [review]
Mainly this comment here needs to be sorted before closing this ticket: https://lifebit.atlassian.net/browse/LP-6169?focusedCommentId=82322

**Comment by mageshwaran-lifebit** [comment]
> Mainly this comment here needs to be sorted before closing this ticket: https://lifebit.atlassian.net/browse/LP-6169?focusedCommentId=82322

@tiagofilipe12 added document https://lifebit.atlassian.net/browse/LP-6169?focusedCommentId=82405

**Review by tiagofilipe12 — APPROVED** [review]
Lgtm, but is the pipeline meant to be failing?

**Comment by mageshwaran-lifebit** [comment]
> Lgtm, but is the pipeline meant to be failing?

Now test is fixed.

**Pull request merged**
